spring:
  main:
    banner-mode: "off"
  data:
    mongodb:
      database: test-db
      username: test
      password: test@123
      host: localhost
      port: 27017
      authentication-database: admin
