version: '3.8'
services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - /tmp/mongo60:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test@123
  web-server:
    image: gitorko/project60:1.0.0
    ports:
      - "8080:8080"
    links:
      - mongodb
    depends_on:
      mongodb:
        condition: service_started
